version: '3.8'

services:
  # Tên dịch vụ Frontend
  frontend:
    build: ./Front_end
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./Front_end:/app
      - /app/node_modules # Giữ lại node_modules trong container để tránh conflict với máy thật
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - tour-booking-network
    depends_on:
      - backend

  # Tên dịch vụ Backend
  backend:
    build: ./Back_end
    container_name: backend_container
    ports:
      - "3000:3000"
    volumes:
      - ./Back_end:/app
      - /app/node_modules
    environment:
      - PORT=3000
    networks:
      - tour-booking-network

networks:
  tour-booking-network:
    driver: bridge
